name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpunit tests --colors --do-not-cache-result